name: unit-tests
on:
  workflow_run:
    workflows: build-webpack
    types: [completed]

jobs:
  unit-tests:
    # if: github.event.workflow_run.event == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - name: Debug context
        env:
          GITHUB_EVENT: ${{ toJSON(github.event) }}
        run: |
          echo "$GITHUB_EVENT"
          echo "---------"
          echo "push SHA to build: TODO"
          echo "PR SHA to build: ${{ github.event.workflow_run.head_sha }}"

      - name: Download webpack artifact
        # 2.14.0; if you update this, audit the diff and ensure that it does not leak/abuse secrets
        uses: dawidd6/action-download-artifact@b9571484721e8187f1fd08147b497129f8972c74
        with:
          workflow: build-webpack
          run_id: ${{ github.event.workflow_run.id }}
          name: webpack
